[package]
name = "custom-crypto-addresses"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "solana-generator"
path = "src/solana_generator.rs"

[dependencies]
solana-sdk = "1.18"
bs58 = "0.5"
serde_json = "1.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1